--------------------------------------------------------
--  File created - Wednesday-January-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "KONICHIWA"."ADDRESS" 
   (	"ADDRESSID" NUMBER, 
	"ADDRESSSTREET" VARCHAR2(50 BYTE), 
	"ADDRESSCITY" VARCHAR2(30 BYTE), 
	"ADDRESSPOSTCODE" VARCHAR2(5 BYTE), 
	"ADDRESSSTATE" VARCHAR2(50 BYTE), 
	"CUSTID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "KONICHIWA"."CUSTOMER" 
   (	"CUSTID" NUMBER DEFAULT NULL, 
	"CUSTFNAME" VARCHAR2(20 BYTE), 
	"CUSTLNAME" VARCHAR2(20 BYTE), 
	"CUSTPHONE" VARCHAR2(15 BYTE), 
	"CUSTEMAIL" VARCHAR2(20 BYTE), 
	"CUSTPASSWORD" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CASHIER
--------------------------------------------------------

  CREATE TABLE "KONICHIWA"."CASHIER" 
   (	"STAFFID" NUMBER, 
	"STAFFTYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------

  CREATE TABLE "KONICHIWA"."ITEM" 
   (	"ITEMID" NUMBER, 
	"ITEMNAME" VARCHAR2(30 BYTE), 
	"ITEMPRICE" NUMBER(4,2), 
	"ITEMSTOCK" NUMBER(*,0), 
	"ITEMDESC" VARCHAR2(100 BYTE), 
	"STAFFID" NUMBER, 
	"ITEMCATEGORYID" NUMBER, 
	"ITEMIMAGE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("ITEMIMAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ITEM_CATEGORY
--------------------------------------------------------

  CREATE TABLE "KONICHIWA"."ITEM_CATEGORY" 
   (	"ITEMCATEGORYID" NUMBER, 
	"CATEGORYNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MASTER_ADMIN
--------------------------------------------------------

  CREATE TABLE "KONICHIWA"."MASTER_ADMIN" 
   (	"STAFFID" NUMBER, 
	"STAFFTYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "KONICHIWA"."ORDER_DETAILS" 
   (	"ORDER_DETAILSID" NUMBER, 
	"ITEM_ORDERQTY" NUMBER(*,0), 
	"ITEMID" NUMBER, 
	"STAFFID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "KONICHIWA"."ORDERS" 
   (	"ORDERS" NUMBER, 
	"TOTALPRICE" NUMBER(5,2), 
	"DELIVERYADRESS" VARCHAR2(100 BYTE), 
	"PAYMENTID" VARCHAR2(20 BYTE), 
	"ORDERSTATUS" VARCHAR2(20 BYTE), 
	"ORDERDATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CUSTID" NUMBER, 
	"STAFFID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "KONICHIWA"."PAYMENT" 
   (	"PAYMENTID" VARCHAR2(20 BYTE), 
	"PAYMENTMETHOD" VARCHAR2(20 BYTE), 
	"DELIVERYFEE" NUMBER(5,2), 
	"TRANSACTIONFEE" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RIDER
--------------------------------------------------------

  CREATE TABLE "KONICHIWA"."RIDER" 
   (	"RIDERID" NUMBER, 
	"RIDERFNAME" VARCHAR2(20 BYTE), 
	"RIDERLNAME" VARCHAR2(20 BYTE), 
	"RIDERPHONE" VARCHAR2(15 BYTE), 
	"RIDEREMAIL" VARCHAR2(20 BYTE), 
	"RIDERPASSWORD" VARCHAR2(20 BYTE), 
	"RIDERVERIFY_STATUS" NUMBER(1,0) DEFAULT 0, 
	"RIDERAVAILABILITY" NUMBER(1,0) DEFAULT 0, 
	"STAFFID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "KONICHIWA"."STAFF" 
   (	"STAFFID" NUMBER, 
	"STAFFFNAME" VARCHAR2(20 BYTE), 
	"STAFFLNAME" VARCHAR2(20 BYTE), 
	"STAFFPHONE" VARCHAR2(15 BYTE), 
	"STAFFEMAIL" VARCHAR2(20 BYTE), 
	"STAFFLPASSWORD" VARCHAR2(8 BYTE), 
	"STAFFTYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KONICHIWA.ADDRESS
SET DEFINE OFF;
Insert into KONICHIWA.ADDRESS (ADDRESSID,ADDRESSSTREET,ADDRESSCITY,ADDRESSPOSTCODE,ADDRESSSTATE,CUSTID) values (41,'Pandan Indah','KL','12345','KL',6);
Insert into KONICHIWA.ADDRESS (ADDRESSID,ADDRESSSTREET,ADDRESSCITY,ADDRESSPOSTCODE,ADDRESSSTATE,CUSTID) values (42,'Puchong','Puchonog','47120','Selangor',6);
Insert into KONICHIWA.ADDRESS (ADDRESSID,ADDRESSSTREET,ADDRESSCITY,ADDRESSPOSTCODE,ADDRESSSTATE,CUSTID) values (43,'efgrg','egrghr','12312','fdgdfh',3);
REM INSERTING into KONICHIWA.CUSTOMER
SET DEFINE OFF;
Insert into KONICHIWA.CUSTOMER (CUSTID,CUSTFNAME,CUSTLNAME,CUSTPHONE,CUSTEMAIL,CUSTPASSWORD) values (3,'Siti','Kasim','0192233221','siti@yahoo.com','siti1234');
Insert into KONICHIWA.CUSTOMER (CUSTID,CUSTFNAME,CUSTLNAME,CUSTPHONE,CUSTEMAIL,CUSTPASSWORD) values (6,'Hanis','Safwah','0192229988','hanissafwh@gmail.com','hanis1');
REM INSERTING into KONICHIWA.CASHIER
SET DEFINE OFF;
REM INSERTING into KONICHIWA.ITEM
SET DEFINE OFF;
REM INSERTING into KONICHIWA.ITEM_CATEGORY
SET DEFINE OFF;
REM INSERTING into KONICHIWA.MASTER_ADMIN
SET DEFINE OFF;
REM INSERTING into KONICHIWA.ORDER_DETAILS
SET DEFINE OFF;
REM INSERTING into KONICHIWA.ORDERS
SET DEFINE OFF;
REM INSERTING into KONICHIWA.PAYMENT
SET DEFINE OFF;
REM INSERTING into KONICHIWA.RIDER
SET DEFINE OFF;
REM INSERTING into KONICHIWA.STAFF
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."ADDRESS_PK" ON "KONICHIWA"."ADDRESS" ("ADDRESSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."CUSTOMER_PK" ON "KONICHIWA"."CUSTOMER" ("CUSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007447
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."SYS_C007447" ON "KONICHIWA"."CASHIER" ("STAFFID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."ITEM_PK" ON "KONICHIWA"."ITEM" ("ITEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ITEM_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."ITEM_CATEGORY_PK" ON "KONICHIWA"."ITEM_CATEGORY" ("ITEMCATEGORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007442
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."SYS_C007442" ON "KONICHIWA"."MASTER_ADMIN" ("STAFFID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDER_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."ORDER_DETAILS_PK" ON "KONICHIWA"."ORDER_DETAILS" ("ORDER_DETAILSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUST_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."CUST_ORDER_PK" ON "KONICHIWA"."ORDERS" ("ORDERS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."PAYMENT_PK" ON "KONICHIWA"."PAYMENT" ("PAYMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RIDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."RIDER_PK" ON "KONICHIWA"."RIDER" ("RIDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007435
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."SYS_C007435" ON "KONICHIWA"."STAFF" ("STAFFID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STAFF_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONICHIWA"."STAFF_UK" ON "KONICHIWA"."STAFF" ("STAFFID", "STAFFTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ADDRESS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONICHIWA"."ADDRESS_TRG" 
BEFORE INSERT ON ADDRESS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KONICHIWA"."ADDRESS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CUSTOMER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONICHIWA"."CUSTOMER_TRG" 
BEFORE INSERT ON CUSTOMER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CUSTID IS NULL THEN
      SELECT CUSTOMERS_SEQ.NEXTVAL INTO :NEW.CUSTID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KONICHIWA"."CUSTOMER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ITEM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONICHIWA"."ITEM_TRG" 
BEFORE INSERT ON ITEM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KONICHIWA"."ITEM_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ITEM_CATEGORY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONICHIWA"."ITEM_CATEGORY_TRG" 
BEFORE INSERT ON ITEM_CATEGORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ITEMCATEGORYID IS NULL THEN
      SELECT ITEM_CATEGORY_SEQ.NEXTVAL INTO :NEW.ITEMCATEGORYID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KONICHIWA"."ITEM_CATEGORY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDER_DETAILS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONICHIWA"."ORDER_DETAILS_TRG" 
BEFORE INSERT ON ORDER_DETAILS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORDER_DETAILSID IS NULL THEN
      SELECT ORDER_DETAILS_SEQ.NEXTVAL INTO :NEW.ORDER_DETAILSID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KONICHIWA"."ORDER_DETAILS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CUST_ORDER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONICHIWA"."CUST_ORDER_TRG" 
BEFORE INSERT ON ORDERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KONICHIWA"."CUST_ORDER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RIDER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONICHIWA"."RIDER_TRG" 
BEFORE INSERT ON RIDER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.RIDERID IS NULL THEN
      SELECT RIDER_SEQ.NEXTVAL INTO :NEW.RIDERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KONICHIWA"."RIDER_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."ADDRESS" MODIFY ("CUSTID" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ADDRESS" MODIFY ("ADDRESSSTATE" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ADDRESS" MODIFY ("ADDRESSPOSTCODE" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ADDRESS" MODIFY ("ADDRESSCITY" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ADDRESS" MODIFY ("ADDRESSSTREET" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ADDRESS" MODIFY ("ADDRESSID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."CUSTOMER" MODIFY ("CUSTPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."CUSTOMER" MODIFY ("CUSTEMAIL" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."CUSTOMER" MODIFY ("CUSTPHONE" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."CUSTOMER" MODIFY ("CUSTLNAME" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."CUSTOMER" MODIFY ("CUSTFNAME" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."CUSTOMER" MODIFY ("CUSTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CASHIER
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."CASHIER" ADD PRIMARY KEY ("STAFFID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."CASHIER" ADD CONSTRAINT "CASHIER_TYPE_CK" CHECK (stafftype = 'CASHIER') ENABLE;
  ALTER TABLE "KONICHIWA"."CASHIER" MODIFY ("STAFFTYPE" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."CASHIER" MODIFY ("STAFFID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."ITEM" ADD CONSTRAINT "ITEM_PK" PRIMARY KEY ("ITEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."ITEM" MODIFY ("ITEMCATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ITEM" MODIFY ("STAFFID" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ITEM" MODIFY ("ITEMDESC" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ITEM" MODIFY ("ITEMPRICE" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ITEM" MODIFY ("ITEMNAME" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ITEM" MODIFY ("ITEMID" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ITEM" MODIFY ("ITEMIMAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEM_CATEGORY
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."ITEM_CATEGORY" ADD CONSTRAINT "ITEM_CATEGORY_PK" PRIMARY KEY ("ITEMCATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."ITEM_CATEGORY" MODIFY ("CATEGORYNAME" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ITEM_CATEGORY" MODIFY ("ITEMCATEGORYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MASTER_ADMIN
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."MASTER_ADMIN" ADD PRIMARY KEY ("STAFFID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."MASTER_ADMIN" ADD CONSTRAINT "MASTER_ADMIN_TYPE_CK" CHECK (stafftype = 'MASTER ADMIN') ENABLE;
  ALTER TABLE "KONICHIWA"."MASTER_ADMIN" MODIFY ("STAFFTYPE" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."MASTER_ADMIN" MODIFY ("STAFFID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_PK" PRIMARY KEY ("ORDER_DETAILSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."ORDER_DETAILS" MODIFY ("STAFFID" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ORDER_DETAILS" MODIFY ("ITEMID" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ORDER_DETAILS" MODIFY ("ITEM_ORDERQTY" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ORDER_DETAILS" MODIFY ("ORDER_DETAILSID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."ORDERS" ADD CONSTRAINT "CUST_ORDER_PK" PRIMARY KEY ("ORDERS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."ORDERS" MODIFY ("STAFFID" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ORDERS" MODIFY ("CUSTID" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ORDERS" MODIFY ("ORDERDATE" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ORDERS" MODIFY ("ORDERSTATUS" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ORDERS" MODIFY ("PAYMENTID" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ORDERS" MODIFY ("DELIVERYADRESS" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ORDERS" MODIFY ("TOTALPRICE" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."ORDERS" MODIFY ("ORDERS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."PAYMENT" ADD CONSTRAINT "PAYMENT_PK" PRIMARY KEY ("PAYMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."PAYMENT" MODIFY ("PAYMENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RIDER
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."RIDER" ADD CONSTRAINT "RIDER_PK" PRIMARY KEY ("RIDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."RIDER" MODIFY ("STAFFID" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."RIDER" MODIFY ("RIDERAVAILABILITY" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."RIDER" MODIFY ("RIDERVERIFY_STATUS" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."RIDER" MODIFY ("RIDERPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."RIDER" MODIFY ("RIDEREMAIL" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."RIDER" MODIFY ("RIDERPHONE" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."RIDER" MODIFY ("RIDERLNAME" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."RIDER" MODIFY ("RIDERFNAME" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."RIDER" MODIFY ("RIDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."STAFF" ADD CONSTRAINT "STAFF_UK" UNIQUE ("STAFFID", "STAFFTYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."STAFF" ADD PRIMARY KEY ("STAFFID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONICHIWA"."STAFF" ADD CONSTRAINT "STAFFTYPE_CK" CHECK (stafftype in ('MASTER ADMIN', 'CASHIER')) ENABLE;
  ALTER TABLE "KONICHIWA"."STAFF" MODIFY ("STAFFTYPE" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."STAFF" MODIFY ("STAFFLPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."STAFF" MODIFY ("STAFFEMAIL" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."STAFF" MODIFY ("STAFFPHONE" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."STAFF" MODIFY ("STAFFLNAME" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."STAFF" MODIFY ("STAFFFNAME" NOT NULL ENABLE);
  ALTER TABLE "KONICHIWA"."STAFF" MODIFY ("STAFFID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK1" FOREIGN KEY ("CUSTID")
	  REFERENCES "KONICHIWA"."CUSTOMER" ("CUSTID") ON DELETE CASCADE DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table CASHIER
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."CASHIER" ADD CONSTRAINT "CASHIER_STAFF_FK" FOREIGN KEY ("STAFFID", "STAFFTYPE")
	  REFERENCES "KONICHIWA"."STAFF" ("STAFFID", "STAFFTYPE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."ITEM" ADD CONSTRAINT "ITEM_FK1" FOREIGN KEY ("ITEMCATEGORYID")
	  REFERENCES "KONICHIWA"."ITEM_CATEGORY" ("ITEMCATEGORYID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MASTER_ADMIN
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."MASTER_ADMIN" ADD CONSTRAINT "MASTER_ADMIN_STAFF_FK" FOREIGN KEY ("STAFFID", "STAFFTYPE")
	  REFERENCES "KONICHIWA"."STAFF" ("STAFFID", "STAFFTYPE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_FK1" FOREIGN KEY ("ITEMID")
	  REFERENCES "KONICHIWA"."ITEM" ("ITEMID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "KONICHIWA"."ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_FK2" FOREIGN KEY ("ORDER_DETAILSID")
	  REFERENCES "KONICHIWA"."ORDERS" ("ORDERS") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "KONICHIWA"."ORDERS" ADD CONSTRAINT "CUST_ORDER_FK1" FOREIGN KEY ("CUSTID")
	  REFERENCES "KONICHIWA"."CUSTOMER" ("CUSTID") ON DELETE CASCADE DISABLE;
